# Website's icon url.
favicon: /favicon.png

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo: DriftKingTW

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-light

# Navigation bar menu links.
menu:
  DriftKingTW's Blog: /en/index.html
  Archives: /en/archives
#  Lifestyle: /categories/LifeStyle
#  Music: /categories/Music
#  Technology: /categories/Technology
  About: /en/about

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: false

# Share plugin settings.
share:
  type: addthis
  install_url: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5dd69be949e18b82

# Comment plugin settings.
comment:
  type: valine
  app_id: mLsnpgAjHr6osBdnRVYoIQpC-MdYXbMMI        # (required) LeanCloud application id
  app_key: zkROC4QzyTeu7fzjhTbxEY0k       # (required) LeanCloud application key
  notify: true           # (optional) receive email notification
  verify: true           # (optional) show verification code
  placeholder: Feel free to leave a comment ! :D   # (optional) comment box placeholder text
  lang: en
  avatar: mp

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/driftkingtw

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/driftkingtw